name: test
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # daily 9AM EST
    - cron: "0 14 * * *"

jobs:
  plenary:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Neovim nightly
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Setup Kitty
      run: |
        curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y xfce4 libxcb-xkb1
        # homebrew is not used but is required to reproduce an issue for a test case
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Start Xvfb
      run: |
        Xvfb :1 -screen 0 1024x768x16 &

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Test kitty-scrollback.nvim
      run: |
        # TODO: improve the env var exports, github actions are making it hard so I gave up for now
        export KITTY_CONFIG_DIRECTORY="$GITHUB_WORKSPACE/tests"
        export PATH=$HOME/.local/kitty.app/bin:/home/linuxbrew/.linuxbrew/bin:$PATH
        export DISPLAY=:1
        export PS1="\[\e[34m\]$ \[\e[m\]"
        echo 'export KITTY_CONFIG_DIRECTORY="$GITHUB_WORKSPACE/tests"' >> "$HOME/.bashrc"
        echo 'export PATH=$HOME/.local/kitty.app/bin:/home/linuxbrew/.linuxbrew/bin:$PATH' >> "$HOME/.bashrc"
        echo 'export DISPLAY=:1' >> "$HOME/.bashrc"
        echo 'export PS1="\[\e[34m\]$ \[\e[m\]"' >> "$HOME/.bashrc"
        make test

